[package]
description = "Server for swhkd to run shell commands at invoking user level."
edition = "2021"
license = "BSD-2-Clause"
name = "swhks"
version = "1.3.0"

[dependencies]
env_logger = "0.11.3"
log = "0.4.22"
nix = "0.26.4"
sysinfo = "0.30.12"
clap = { version = "4.5.8", features = ["derive"] }

[[bin]]
name = "swhks"
path = "src/main.rs"
